{% set version = "0.8.4" %}

package:
  name: sqlalchemy-redshift
  version: {{ version }}

source:
  url: https://github.com/sqlalchemy-redshift/sqlalchemy-redshift/archive/{{ version }}.tar.gz
  sha256: 2dbd8ea4c62844e164e1e615924808f918fe6d3fd094214c1fc6fd17fa4fef03

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python =2.7|>=3.4
    - pip
  run:
    - python =2.7|>=3.4
    - setuptools
    - sqlalchemy >=0.9.2,<2.0.0
    - psycopg2 >=2.5

test:
  imports:
    - sqlalchemy_redshift

about:
  home: https://github.com/sqlalchemy-redshift/sqlalchemy-redshift
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Amazon Redshift SQLAlchemy Dialect

  doc_url: https://sqlalchemy-redshift.readthedocs.io/en/latest/
  dev_url: https://github.com/sqlalchemy-redshift/sqlalchemy-redshift

extra:
  recipe-maintainers:
    - mcg1969
    - synapticarbors
    - igorborgest
