{% set version = "0.7.7" %}

package:
  name: sqlalchemy-redshift
  version: {{ version }}

source:
  url: https://github.com/sqlalchemy-redshift/sqlalchemy-redshift/archive/{{ version }}.tar.gz
  sha256: 5222aff4aee7536ac09c5ed882571f98924034622e0eb168927041470d095e9c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - setuptools
    - sqlalchemy >=0.9.2,<2.0.0
    - psycopg2 >=2.5

test:
  imports:
    - sqlalchemy_redshift

about:
  home: https://github.com/sqlalchemy-redshift/sqlalchemy-redshift
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Amazon Redshift SQLAlchemy Dialect'

  doc_url: https://sqlalchemy-redshift.readthedocs.io/en/latest/
  dev_url: https://github.com/sqlalchemy-redshift/sqlalchemy-redshift

extra:
  recipe-maintainers:
    - mcg1969
    - synapticarbors
    - igorborgest
