travis:
  secure:
    BINSTAR_TOKEN: zWRpdDTHkRo9x3D9wKggseYt6aYmwOhCCKK2x5eNCFWoTYp5rSwe2xDJC8r1lv9JDFzW7jIEjNr8DVNRKyhYN43wrF12DlygUfAS9az6IZotLuGeMJITKDW7K0KQtF/qzdgWzqqVbhzGbtXrpUqJFy4SLQ+t+qcLDFWFWYQNbPTgjO47Qa7RoBUoyNusCM3hiQJrBqHy8OCiLscilqV79uVjmmUhHXMBV2j2658QVg5VUfOStVaNMbqItziXNw64Xp3zP+6d/nIVq4rIVYk22JqKVDU4aQO817+cuOr55qpj1B8gfezq5JuMoYN1NnvhRiwErg455jmNZgbXb8KIkuX/QhSc5tiNXSK+6G5JuCrPjugKT9H2Mmk/4YOWqoSr5X3n2OuQOIQdDjWrBkxyDvSjGepHUx05Q5B/3qXUoXVfiRHfkyQFVyCxNksqMir87/8KZldTGKIfqPOXOuldd1H/qj/EZD48qMFEPrUnpdlYSqTy4YlwGanUM1f+PGw/RFS9KJi3ScXbnUmW+8V3WYMwtNVtjhj/loNINW67aGNH5knOTIgugHJB56QAPBwJg0WMRH0Vvyqgw6+e9UTWTcaCIbmY++lrEzF/FFzwRJS0/faDDqN2Lqw5MEOv529aK9OhZBgDlWr/Bae7J6oInpfPIupQESdtMiVbsErIsMk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
