travis:
  secure:
    BINSTAR_TOKEN: nAaTP6EVdX6+zwW5sDGsb1I4w3Ma4B+nO6RTL2eHFsuDRqEbqZkZpi6cZXuy9ThWHpKyNzbjdt2uHce+gyr0CERhCLaAemUnRRZY7zz0qJR+6WyjwG/TAIvPkor5Y75sa/KQlzsEtX6Ze0ET2J8gsTmvbzcOheBNJZrKsiBdX7MO+KidH9gmDCIVQGx59qt7QZ93ONAvX/2sjeug2mk/EKjElH2I8Lr9U65BMJ40R6eUcLUsJqyCpOmTxUe34RBtuo46AoJYnAGS2jIgLYZ1SRsSgbRrhgBqURmRps+sJQ/VR9T+DqWNoMdo1xbSoP3aqlzl/IttshIAH+79A7WIvDvyIKtqDe3AJcNNY7zz/+s5NLeiv6zrbNTwWyTZ+W1cyenC4CIRWp8U2KWbIauiaIXW1nJZh47IIEIwM49JYAe+3bgbfgqDLXSNdRqkqre4lEO1RQQSafY2ATMEOuIlf6jlbPoRESLjsneI6KmPEtH1TKc2kMy5UtiHDgixTqEd8dCvXzjsfJovTmc00UrewPqCxNMiUVrAL8P9YMwF1SxPuhxUQK68jNk0sJXmld4cv62YEjvOMZ74RJse7N6tASTOvIuFSrOGk3Au+O6R3Nd1qOL9nUos72Xy8DiopkVC+mKh6nfB9PmrQTfdTocmUihU+ImB9OJ5FMLIg/XT8CI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
