travis:
  secure:
    BINSTAR_TOKEN: j+irBs0rrJ8S7Ni7h4AYqN2GzWoZ2oHECu/NSULXEUUK1q7UH7CVptqqEd4O4mIa01r4Jpl0d9Y4Gx7Z9IqnBG/mumV62l13tLFn0Xr0lWgW1s+glxDZBXaJpADn2hSSjOn8uvNX+5VVCjOm0Ex1/VLgLEbmqqIGKg1U6Gd8/qhyxM3+ghDQy3uiMSZynyP8vwy+/xLp5bIeIhbKRTe+NqghGfrzWsWE4qyW4VissGQm+voI6hU15r5++r9SCWLrpWEPfAJcd2utunl3kz23h9JiuPPjaZ7r4ayeTE0QWTnnszQJjHuPJdUzSUc4W0CbWB/qtqqXOeXXtys9xqNONjBJ2rrQFs7NkX0+tpxj/CtuTcoIPyz8a3DVNB89AEKN/4SarfL3ovkd93SUL63JkM6iTAnq0LytLFa+gIIUkw7c2uwky+MDZ/ZZp5/x96UkwxaVDEJ60F2qC4n3p0yYqUERGR5VrkLs5bsWW5VbLV/1mxTzXR4mXBQZ93wfZENzgFQc75TysPQGNoN9ky+6uaVg2mmVDcMAQMU7Vq4f4vvnFTnE6IgJPOaCKeJTjQvEHGS2RZNy/NDNR+ox20uOyyp0ZdV1aGokCMbXQbmv/YvaNcLlnPS+kLbl/gRVdmWcGjCW7XV+BaD63/2EAid30anIDI9bsxR2W9QaDCU7Wk0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
